using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._BRatbite.Kitchen.UI;


[GenerateTypedNameReferences]
public sealed partial class ContainerCookerMenu : FancyWindow
{
    public bool IsBusy;

    public ContainerCookerMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetPanelDisabled(bool disable)
    {
        DisableCookingPanelOverlay.Visible = disable;
    }
}
