using Content.Client.Kitchen.UI;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._BRatbite.Kitchen.UI;


[GenerateTypedNameReferences]
public sealed partial class CookwareMenu : FancyWindow
{

    public CookwareMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

}

