using System.Globalization;
using Content.Client.Kitchen.UI;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._BRatbite.Kitchen.UI;

/// <summary>
/// Manages rendering and creation of the TimedCookerMenu.
/// Based on <see cref="MicrowaveMenu"/>
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TimedCookerMenu : FancyWindow
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    /// <summary>
    /// the unsigned integer here is just the index of the button
    /// </summary>
    public event Action<BaseButton.ButtonEventArgs, int>? OnCookTimeButtonPress;

    private ButtonGroup CookTimeButtonGroup { get; }

    /// <summary>
    /// Whether to disable the UI (true when cooking)
    /// </summary>
    public bool IsBusy;

    /// <summary>
    /// When the recipe is finished and we are done cooking. (null when not cooking)
    /// </summary>
    public TimeSpan? RecipeEnd;

    /// <summary>
    /// Constructor for <see cref="TimedCookerMenu"/>
    /// </summary>
    public TimedCookerMenu()
    {
        RobustXamlLoader.Load(this);
        CookTimeButtonGroup = new ButtonGroup();
        InstantCookButton.Group = CookTimeButtonGroup;
        InstantCookButton.OnPressed += args =>
        {
            OnCookTimeButtonPress?.Invoke(args, 0);
        };
    }

    public uint[] SetPresets(uint[] cookTimePresets, float cookTimeMultiplier)
    {
        var timesWithMultiplier = new uint[cookTimePresets.Length];
        for (var i = 0; i < cookTimePresets.Length; i++)
        {
            var time = (uint) Math.Ceiling(cookTimePresets[i] * cookTimeMultiplier);
            timesWithMultiplier[i] = time;
            var timeButton = new CookTimeButton
            {
                Text = time.ToString(CultureInfo.InvariantCulture),
                TextAlign = Label.AlignMode.Center,
                ToggleMode = true,
                Group = CookTimeButtonGroup,
                HorizontalExpand = true,
                StyleClasses = { "OpenBoth" },
            };

            CookTimeButtonVbox.AddChild(timeButton);

            var index = i;
            timeButton.OnPressed += args =>
            {
                OnCookTimeButtonPress?.Invoke(args, index + 1); // 0 is instant
            };
        }
        return timesWithMultiplier;
    }

    public void SetPanelDisabled(bool disable)
    {
        DisableCookingPanelOverlay.Visible = disable;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!IsBusy)
            return;

        if (RecipeEnd.HasValue && RecipeEnd.Value > _gameTiming.CurTime)
        {
            CookTimeInfoLabel.Text = Loc.GetString("microwave-bound-user-interface-cook-time-label",
                ("time", Math.Ceiling(RecipeEnd.Value.Subtract(_gameTiming.CurTime).TotalSeconds)));
        }
    }

    public sealed class CookTimeButton : Button;
}
